AllCops:
  Exclude:
    - 'tmp/**/*'

Style/CommentedKeyword:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/**/*.rake'
    - 'lib/smart_answer_flows/**/*.rb'
    - 'test/**/*.rb'
    - 'spec/**/*.rb'
